### ISSUE TITLE
Not working and no instructions

### ISSUE THREAD

**Issue by Surabi84** [Lunahax/VALORANT-EXTERNAL#13]
Hey Lunar.. 
i bought @ discord. Got the version:
val_external_1.1.1.zip
and a ID for it from your discord. 

I copied all files into: 
D:\Games\valorant\Riot Games\VALORANT\live\

this is the folder where my .exe from valorant is located. So they told me @ your discord. Now I Run hack as Administrator. Menu opend, then insert the key i got. Adjust aimbot, ESP Settings and so.. last is saving it. I press Save and the window is open all the time and nothing happens. Longer thant the 120seconds wich are written. Then i start valorant. Windowed Mode and rawbuffer off is already set.. but nothing is happening ingame. 

What is wrong? Firewall off / live security off / antivir off

**Comment by Lunahax** [comment]
We are aware of the issue that it doesn't seem to inject on certain devices - we are looking for a fix, update will follow monday
