### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by Surabi84** [Lunahax/VALORANT-EXTERNAL#15]
Idk if possible @ valorant but it would be nice to have:

- headdot esp
- backtrack? 
- config loader ( f.e. legit/semi-rage/rage)
- sound-esp
- hitmarker (visual/sound)

**Comment by ValorantExternal** [comment]
LunaR, server administrator, here. Highly appreciate the feedback! Mind giving me your Discord#Tag? Alune and I will definitely try to add your suggestions into 1.2 / 1.3 and we also may have a small surprise for you ;)

**Comment by Lunahax** [comment]
Noted down, thank you for your feedback :)
